server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /bench/ {
        proxy_pass http://backend:8080/bench/;
        proxy_set_header Host $host;
        proxy_read_timeout 600s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
